#
# board/calixto/rzv2l-optima/Makefile
#
# CALIXTO SYSTEMS PVT LTD
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:=  ../../renesas/rcar-common/rcar-common/gen3-spl.o
else
obj-y	:= rzv2l-optima.o ../../renesas/rcar-common/common.o
endif
